name: main_workflow
on:
  push:
    branches:
      - nodejs_jest_job
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_linter_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true

  test-execution:
    needs: linter-execution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install jest
      - run: npm test
        id: world
        continue-on-error: true
      - name: Check on failures
        if: job.steps.hello.status == failure() || job.steps.world.status == failure()
        # uses: dawidd6/action-send-mail@v3
        # with:
        #   connection_url: ${{secrets.MAIL_CONNECTION}}
        #   server_address: smtp.gmail.com
        #   server_port: 465
        #   secure: true
        #   # username: ${{secrets.MAIL_USERNAME}}
        #   # password: ${{secrets.MAIL_PASSWORD}}
        #   subject: Github Actions job result
        #   to: juanluislopezdaw@gmail.com
        #   from: juanluislopezdaw@gmail.com
        #   body: Build job of ${{github.repository}} completed successfully!
